export async function seed(knex) {
  await knex('users').insert([
    {
      id: 'auth0|6478f3fd75374ee3d7bc4d94',
      username: 'johnpeace',
      name: 'John Mindful',
      email: 'john@example.com',
      phone: '+64 21 723 432',
      my_equipment: JSON.stringify(
        {
          backpack: false,
          waterproof_pack_liner: false,
          sleeping_bag: false,
          first_aid_kit: false,
          survival_kit: false,
          safety_equipment: false,
          torch_flashlight: false,
          rubbish_bag: false,
          booking_confirmation_and_id: false,
          earplugs_for_bunkrooms: false,
          drink_bottle: false,
          eating_and_cooking_utensils: false,
          gas_cooker_and_fuel: false,
          matches_or_lighter: false,
          general_toiletries: false,
          backup_toilet_option: false,
          tent: false,
          sleeping_mat: false,
          ground_sheet: false,
          walking_clothes: false,
          hiking_boots: false,
          socks: false,
          shorts: false,
          shirt: false,
          under_layers: false,
          mid_layers: false,
          raincoat: false,
          overtrousers: false,
          warm_hat_and_gloves: false,
          sunhat_and_sunglasses: false,
          extra_socks_underwear_and_shirt: false,
          gaiters: false,
          lightweight_shoes_for_huts: false,
          carry_food: false,
          lightweight_food: false,
          emergency_food: false,
          food_storage: false,
          emergency_shelter: false,
          distress_beacon: false,
          cooking_facilities: false,
          sanitary_bins: false,
          gas_cooker: false,
          fire_starters: false,
          life_jacket: false,
          kayak_or_canoe: false,
          paddles: false,
          plastic_drums_or_equivalent: false,
          dry_bags: false,
          swimwear: false,
          sandals_or_aqua_shoes: false,
          portable_stove_and_fuel: false,
          candles: false,
          doc_confirmation_letter: false,
        },
        null,
        2,
      ),
      result: '',
    },
    {
      id: 'auth0|648fd1c873375442becf2c60',
      username: 'daphattack',
      name: 'Daph Simons',
      email: 'daph@example.com',
      phone: '+64 27 891 234',
      my_equipment: JSON.stringify(
        {
          backpack: false,
          waterproof_pack_liner: false,
          sleeping_bag: false,
          first_aid_kit: false,
          survival_kit: false,
          safety_equipment: false,
          torch_flashlight: false,
          rubbish_bag: false,
          booking_confirmation_and_id: false,
          earplugs_for_bunkrooms: false,
          drink_bottle: false,
          eating_and_cooking_utensils: false,
          gas_cooker_and_fuel: false,
          matches_or_lighter: false,
          general_toiletries: false,
          backup_toilet_option: false,
          tent: false,
          sleeping_mat: false,
          ground_sheet: false,
          walking_clothes: false,
          hiking_boots: false,
          socks: false,
          shorts: false,
          shirt: false,
          under_layers: false,
          mid_layers: false,
          raincoat: false,
          overtrousers: false,
          warm_hat_and_gloves: false,
          sunhat_and_sunglasses: false,
          extra_socks_underwear_and_shirt: false,
          gaiters: false,
          lightweight_shoes_for_huts: false,
          carry_food: false,
          lightweight_food: false,
          emergency_food: false,
          food_storage: false,
          emergency_shelter: false,
          distress_beacon: false,
          cooking_facilities: false,
          sanitary_bins: false,
          gas_cooker: false,
          fire_starters: false,
          life_jacket: false,
          kayak_or_canoe: false,
          paddles: false,
          plastic_drums_or_equivalent: false,
          dry_bags: false,
          swimwear: false,
          sandals_or_aqua_shoes: false,
          portable_stove_and_fuel: false,
          candles: false,
          doc_confirmation_letter: false,
        },
        null,
        2,
      ),
      result: '',
    },
    {
      id: 'auth0|649024f773375442becf3102',
      username: 'gerard',
      name: 'Gerard',
      email: 'gerard@example.com',
      phone: '+64 22 345 678',
      my_equipment: JSON.stringify(
        {
          backpack: false,
          waterproof_pack_liner: false,
          sleeping_bag: false,
          first_aid_kit: false,
          survival_kit: false,
          safety_equipment: false,
          torch_flashlight: false,
          rubbish_bag: false,
          booking_confirmation_and_id: false,
          earplugs_for_bunkrooms: false,
          drink_bottle: false,
          eating_and_cooking_utensils: false,
          gas_cooker_and_fuel: false,
          matches_or_lighter: false,
          general_toiletries: false,
          backup_toilet_option: false,
          tent: false,
          sleeping_mat: false,
          ground_sheet: false,
          walking_clothes: false,
          hiking_boots: false,
          socks: false,
          shorts: false,
          shirt: false,
          under_layers: false,
          mid_layers: false,
          raincoat: false,
          overtrousers: false,
          warm_hat_and_gloves: false,
          sunhat_and_sunglasses: false,
          extra_socks_underwear_and_shirt: false,
          gaiters: false,
          lightweight_shoes_for_huts: false,
          carry_food: false,
          lightweight_food: false,
          emergency_food: false,
          food_storage: false,
          emergency_shelter: false,
          distress_beacon: false,
          cooking_facilities: false,
          sanitary_bins: false,
          gas_cooker: false,
          fire_starters: false,
          life_jacket: false,
          kayak_or_canoe: false,
          paddles: false,
          plastic_drums_or_equivalent: false,
          dry_bags: false,
          swimwear: false,
          sandals_or_aqua_shoes: false,
          portable_stove_and_fuel: false,
          candles: false,
          doc_confirmation_letter: false,
        },
        null,
        2,
      ),
      result: '',
    },
  ])
}
