export async function seed(knex) {
  await knex('users').insert([
    {
      id: 'auth0|6478f3fd75374ee3d7bc4d94',
      username: 'johnpeace',
      name: 'John Mindful',
      email: 'john@example.com',
      phone: '+64 21 723 432',
      my_equipment: JSON.stringify(
        {
          backpack: false,
          waterproofPackLiner: false,
          sleepingBag: false,
          firstAidKit: false,
          survivalKit: false,
          safetyEquipment: false,
          torchFlashlight: false,
          rubbishBag: false,
          bookingConfirmationAndId: false,
          earplugsForBunkrooms: false,
          drinkBottle: false,
          eatingAndCookingUtensils: false,
          gasCookerAndFuel: false,
          matchesOrLighter: false,
          generalToiletries: false,
          backupToiletOption: false,
          tent: false,
          sleepingMat: false,
          groundSheet: false,
          walkingClothes: false,
          hikingBoots: false,
          socks: false,
          shorts: false,
          shirt: false,
          underLayers: false,
          midLayers: false,
          raincoat: false,
          overtrousers: false,
          warmHatAndGloves: false,
          sunhatAndSunglasses: false,
          extraSocksUnderwearAndShirt: false,
          gaiters: false,
          lightweightShoesForHuts: false,
          carryFood: false,
          lightweightFood: false,
          emergencyFood: false,
          foodStorage: false,
          emergencyShelter: false,
          distressBeacon: false,
          cookingFacilities: false,
          sanitaryBins: false,
          gasCooker: false,
          fireStarters: false,
          lifeJacket: false,
          kayakOrCanoe: false,
          paddles: false,
          plasticDrumsOrEquivalent: false,
          dryBags: false,
          swimwear: false,
          sandalsOrAquaShoes: false,
          portableStoveAndFuel: false,
          candles: false,
          docConfirmationLetter: false,
        },
        null,
        2,
      ),
      result: '',
    },
    {
      id: 'auth0|648fd1c873375442becf2c60',
      username: 'daphattack',
      name: 'Daph Simons',
      email: 'daph@example.com',
      phone: '+64 27 891 234',
      my_equipment: JSON.stringify(
        {
          backpack: false,
          waterproofPackLiner: false,
          sleepingBag: false,
          firstAidKit: false,
          survivalKit: false,
          safetyEquipment: false,
          torchFlashlight: false,
          rubbishBag: false,
          bookingConfirmationAndId: false,
          earplugsForBunkrooms: false,
          drinkBottle: false,
          eatingAndCookingUtensils: false,
          gasCookerAndFuel: false,
          matchesOrLighter: false,
          generalToiletries: false,
          backupToiletOption: false,
          tent: false,
          sleepingMat: false,
          groundSheet: false,
          walkingClothes: false,
          hikingBoots: false,
          socks: false,
          shorts: false,
          shirt: false,
          underLayers: false,
          midLayers: false,
          raincoat: false,
          overtrousers: false,
          warmHatAndGloves: false,
          sunhatAndSunglasses: false,
          extraSocksUnderwearAndShirt: false,
          gaiters: false,
          lightweightShoesForHuts: false,
          carryFood: false,
          lightweightFood: false,
          emergencyFood: false,
          foodStorage: false,
          emergencyShelter: false,
          distressBeacon: false,
          cookingFacilities: false,
          sanitaryBins: false,
          gasCooker: false,
          fireStarters: false,
          lifeJacket: false,
          kayakOrCanoe: false,
          paddles: false,
          plasticDrumsOrEquivalent: false,
          dryBags: false,
          swimwear: false,
          sandalsOrAquaShoes: false,
          portableStoveAndFuel: false,
          candles: false,
          docConfirmationLetter: false,
        },
        null,
        2,
      ),
      result: '',
    },
    {
      id: 'auth0|649024f773375442becf3102',
      username: 'gerard',
      name: 'Gerard',
      email: 'gerard@example.com',
      phone: '+64 22 345 678',
      my_equipment: JSON.stringify(
        {
          backpack: false,
          waterproofPackLiner: false,
          sleepingBag: false,
          firstAidKit: false,
          survivalKit: false,
          safetyEquipment: false,
          torchFlashlight: false,
          rubbishBag: false,
          bookingConfirmationAndId: false,
          earplugsForBunkrooms: false,
          drinkBottle: false,
          eatingAndCookingUtensils: false,
          gasCookerAndFuel: false,
          matchesOrLighter: false,
          generalToiletries: false,
          backupToiletOption: false,
          tent: false,
          sleepingMat: false,
          groundSheet: false,
          walkingClothes: false,
          hikingBoots: false,
          socks: false,
          shorts: false,
          shirt: false,
          underLayers: false,
          midLayers: false,
          raincoat: false,
          overtrousers: false,
          warmHatAndGloves: false,
          sunhatAndSunglasses: false,
          extraSocksUnderwearAndShirt: false,
          gaiters: false,
          lightweightShoesForHuts: false,
          carryFood: false,
          lightweightFood: false,
          emergencyFood: false,
          foodStorage: false,
          emergencyShelter: false,
          distressBeacon: false,
          cookingFacilities: false,
          sanitaryBins: false,
          gasCooker: false,
          fireStarters: false,
          lifeJacket: false,
          kayakOrCanoe: false,
          paddles: false,
          plasticDrumsOrEquivalent: false,
          dryBags: false,
          swimwear: false,
          sandalsOrAquaShoes: false,
          portableStoveAndFuel: false,
          candles: false,
          docConfirmationLetter: false,
        },
        null,
        2,
      ),
      result: '',
    },
  ])
}
