import { GreatWalk } from '../../models/great_walk'
import connection from './connection'

export async function getWalkById(walkId: number) {
  const walk = await connection('great_walks').where('id', walkId).first()
  console.log(walk)
  const {
    id,
    name,
    difficulty,
    elevation,
    duration,
    distance,
    location,
    description,
    seasonal,
    required_equipment,
    track_image_url,
    doc_link,
  } = walk
  const newValue = await JSON.parse(required_equipment)
  // console.log(newValue)
  // destructure all the equipment values
  const {
    backpack,
    waterproof_pack_liner,
    sleeping_bag,
    first_aid_kit,
    survival_kit,
    safety_equipment,
    torch_flashlight,
    rubbish_bag,
    booking_confirmation_and_id,
    earplugs_for_bunkrooms,
    drink_bottle,
    eating_and_cooking_utensils,
    gas_cooker_and_fuel,
    matches_or_lighter,
    general_toiletries,
    backup_toilet_option,
    tent,
    sleeping_mat,
    ground_sheet,
    walking_clothes,
    hiking_boots,
    socks,
    shorts,
    shirt,
    under_layers,
    mid_layers,
    raincoat,
    overtrousers,
    warm_hat_and_gloves,
    sunhat_and_sunglasses,
    extra_socks_underwear_and_shirt,
    gaiters,
    lightweight_shoes_for_huts,
    carry_food,
    lightweight_food,
    emergency_food,
    food_storage,
    emergency_shelter,
    distress_beacon,
    cooking_facilities,
    sanitary_bins,
    gas_cooker,
    fire_starters,
    life_jacket,
    kayak_or_canoe,
    paddles,
    plastic_drums_or_equivalent,
    dry_bags,
    swimwear,
    sandals_or_aqua_shoes,
    portable_stove_and_fuel,
    candles,
    doc_confirmation_letter,
  } = newValue
  console.log('req', newValue)

  const jsWalk = {
    id,
    name,
    difficulty,
    elevation,
    duration,
    distance,
    location,
    description,
    seasonal,
    trackImageUrl: track_image_url,
    docLink: doc_link,
    requiredEquipment: {
      backpack,
      waterproofPackLiner: waterproof_pack_liner,
      sleepingBag: sleeping_bag,
      firstAidKit: first_aid_kit,
      survivalKit: survival_kit,
      safetyEquipment: safety_equipment,
      torchFlashlight: torch_flashlight,
      rubbishBag: rubbish_bag,
      bookingConfirmationAndId: booking_confirmation_and_id,
      earplugsForBunkrooms: earplugs_for_bunkrooms,
      drinkBottle: drink_bottle,
      eatingAndCookingUtensils: eating_and_cooking_utensils,
      gasCookerAndFuel: gas_cooker_and_fuel,
      matchesOrLighter: matches_or_lighter,
      generalToiletries: general_toiletries,
      backupToiletOption: backup_toilet_option,
      tent,
      sleepingMat: sleeping_mat,
      groundSheet: ground_sheet,
      walkingClothes: walking_clothes,
      hikingBoots: hiking_boots,
      socks,
      shorts,
      shirt,
      underLayers: under_layers,
      midLayers: mid_layers,
      raincoat,
      overtrousers: overtrousers,
      warmHatAndGloves: warm_hat_and_gloves,
      sunhatAndSunglasses: sunhat_and_sunglasses,
      extraSocksUnderwearAndShirt: extra_socks_underwear_and_shirt,
      gaiters,
      lightweightShoesForHuts: lightweight_shoes_for_huts,
      carryFood: carry_food,
      lightweightFood: lightweight_food,
      emergencyFood: emergency_food,
      foodStorage: food_storage,
      emergencyShelter: emergency_shelter,
      distressBeacon: distress_beacon,
      cookingFacilities: cooking_facilities,
      sanitaryBins: sanitary_bins,
      gasCooker: gas_cooker,
      fireStarters: fire_starters,
      lifeJacket: life_jacket,
      kayakOrCanoe: kayak_or_canoe,
      paddles,
      plasticDrumsOrEquivalent: plastic_drums_or_equivalent,
      dryBags: dry_bags,
      swimwear,
      sandalsOrAquaShoes: sandals_or_aqua_shoes,
      portableStoveAndFuel: portable_stove_and_fuel,
      candles,
      docConfirmationLetter: doc_confirmation_letter,
    },
  }
  console.log(jsWalk)
  // converted / alias all snake case to camel case

  return jsWalk as GreatWalk
}

export async function getAllWalks() {
  const walks = await connection('great_walks')
  return walks
}
